spring:
  application:
    name: ledger-core

  datasource:
    url: jdbc:postgresql://localhost:5432/ledger
    username: ledger
    password: ledger

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080